### ISSUE TITLE
Add missing semicolons automatically rather than sass-convert throwing error

### ISSUE THREAD

**Issue by owenleonard** [badsyntax/SassBeautify#115]
I noticed that if there is a semicolon missing, sass-convert throws an error and SassBeautify doesn't complete.  Rather than just displaying the error, it would be nice to have SassBeautify add semicolons automatically.  Sure, a linter will show you the missing semicolons, but it is so much easier to just have SassBeautify add them for me.

For example, in the following code, lines 2, 4, and 12 are each missing a semicolon and will each cause sass-convert to fail.

``` css
// @import '_common';
@import "_colors"

$variable: 35

//TODO: eat pizza
//      and other things

.ClassA,
.ClassB
{
    height: 14px
    font-size: 2em;
    margin: -3px 0 !important;
}
```
