### ISSUE TITLE
blanklineBetweenSelectors has a failing case

### ISSUE THREAD

**Issue by owenleonard** [badsyntax/SassBeautify#37]
When I run SassBeautify with blanklineBetweenSelectors set to true, the following:

``` scss
.class-one,
.class-two,
.class-three {
    background-color: $aaa;
}
```

becomes:

``` scss
.class-one,
.class-two,

.class-three {
    background-color: $aaa;
}
```

I found the regex code that deals with this

``` python
        # Insert a blank line between selectors. (Issue #30)
        if self.get_type() == 'scss' and self.settings.get('blanklineBetweenSelectors', False):
            output = re.sub(r'\n\n\n', '\n\n', re.sub(r'(.*)\{', r'\n\1{', output).strip())
```

This obviously requires the code to search back previous lines of scss until it finds the first one in the list.  I'll keep thinking to see if I can come up with a solution.  Might be easier to do this while the file is split up by line (where you're making sure the file uses unix-style newline characters).

By the way, I ran into this while trying to use SassBeautify in conjunction with SublimeLinter-contrib-scss-lint.  It has a rule for a single selector per line.  I'm finding that sass-convert isn't very compatible with scss-lint.
