### ISSUE TITLE
blanklineBetweenSelectors separates comments from code

### ISSUE THREAD

**Issue by georgecrawford** [badsyntax/SassBeautify#38]
Thanks for this useful tool.

Beautifying a .scss file will expand

``` scss
.test1 {
    display: block;
}

// Comment
.test2 {
    display: block;
}
```

to:

``` scss
.test1 {
    display: block;
}

// Comment

.test2 {
    display: block;
}
```

This separation of comment and associated code block is probably not intended behaviour.
